import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="vi"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta charSet="utf-8" />
        <link rel="icon" href="/public/icon-nnv.jpg" />
        <meta name="description" content="Quản lý nông sản"></meta>
        <meta name="author" content="Nhà Nông Mới"></meta>
        <meta
          name="keywords"
          content="nông sản, nhà nông mới, quản lý nông sản"
        ></meta>
        <meta name="robots" content="index, follow"></meta>
        <meta
          name="image"
          content="https://domain.com/link-cai-anh-thumbnail.jpg"
        ></meta>
        <title>Nhà Nông Mới</title>
      </head>
      <body className="min-h-full flex flex-col">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
